"""Initial migration

Revision ID: 979fa69717d4
Revises: 
Create Date: 2026-06-05 03:15:02.721074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '979fa69717d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Category primary key'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Category name (e.g. 'Obat Resep', 'Obat Bebas')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Category description'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag; False hides category from UI'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Role primary key (auto-increment integer — small table)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Role name, e.g. 'admin', 'apoteker', 'kasir', 'pasien'"),
    sa.Column('description', sa.String(length=255), nullable=True, comment="Human-readable description of the role's permissions"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Supplier primary key'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Supplier / distributor company name'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='Name of the primary contact at the supplier'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Supplier contact phone number'),
    sa.Column('email', sa.String(length=150), nullable=True, comment='Supplier contact email address'),
    sa.Column('address', sa.Text(), nullable=True, comment='Supplier physical address'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Product internal PK'),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='Stock Keeping Unit — globally unique product code'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Drug/product name (indexed for text search)'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='FK → categories.id (M:1 — product belongs to one category)'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='FK → suppliers.id (M:1 — product sourced from one supplier)'),
    sa.Column('description', sa.Text(), nullable=True, comment='General drug description'),
    sa.Column('composition', sa.Text(), nullable=True, comment='Active ingredient composition'),
    sa.Column('dosage', sa.Text(), nullable=True, comment='Dosage instructions'),
    sa.Column('side_effects', sa.Text(), nullable=True, comment='Known side effects'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Retail selling price per unit (IDR)'),
    sa.Column('requires_prescription', sa.Boolean(), server_default='false', nullable=False, comment='True = obat keras; purchase requires pharmacist-approved prescription'),
    sa.Column('min_stock_threshold', sa.Integer(), server_default='10', nullable=False, comment='Minimum stock before NOTIF-01 low-stock alert fires'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='Relative or absolute path to the product image'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag; False removes product from catalogue API'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_fulltext', 'products', ['name', 'description'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops', 'description': 'gin_trgm_ops'})
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Internal BigInteger PK — never expose in public APIs'),
    sa.Column('uuid', sa.String(length=36), server_default=sa.text('CAST(gen_random_uuid() AS VARCHAR)'), nullable=False, comment='RFC-4122 UUID for public-facing references (hides sequential IDs)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full name of the user'),
    sa.Column('email', sa.String(length=150), nullable=False, comment='Login email — must be globally unique'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt or Argon2 hash of the user password'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Contact phone number (optional)'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='FK → roles.id (M:1 — every user has exactly one role)'),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='True after OTP email verification is completed'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-disable: set False to lock account without deletion'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp of the most recent successful login'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last profile update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Audit log PK'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='FK → users.id — who performed the action. Nullable so logs survive if the user account is later deleted.'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Semantic action name in SCREAMING_SNAKE_CASE, e.g. LOGIN, LOGOUT, CREATE_PRODUCT, UPDATE_STOCK, PLACE_ORDER'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='Application module that generated this log, e.g. AUTH, PRODUCT, ORDER'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='ORM entity/table name of the affected record, e.g. Product, Order'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='PK of the affected entity row (NULL for non-entity actions like LOGIN)'),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Serialised state of the entity BEFORE the change (JSONB)'),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Serialised state of the entity AFTER the change (JSONB)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (supports both IPv4 and IPv6 — max 45 chars)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Full User-Agent header string from the HTTP request'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when the event occurred — never mutated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Order internal PK'),
    sa.Column('order_code', sa.String(length=20), nullable=False, comment='Formatted order code e.g. ORD-20250601-001 — shown to customers'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK → users.id — the customer who placed this order'),
    sa.Column('cashier_id', sa.BigInteger(), nullable=True, comment='FK → users.id (Kasir role) — NULL for online orders'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'READY', 'COMPLETED', 'CANCELLED', name='order_status_enum'), server_default='PENDING', nullable=False, comment='Current lifecycle status of the order'),
    sa.Column('order_type', sa.Enum('ONLINE', 'COUNTER', name='order_type_enum'), nullable=False, comment="Channel: 'online' (web) or 'counter' (POS/kasir)"),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False, comment='Sum of (unit_price × quantity) for all items before discounts/tax'),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False, comment='Total discount amount applied (IDR)'),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False, comment='PPN 11% tax amount (IDR)'),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False, comment='Final payable amount: subtotal - discount + tax (IDR)'),
    sa.Column('payment_method', sa.Enum('CASH', 'TRANSFER', 'QRIS', name='payment_method_enum'), nullable=False, comment='Selected payment instrument'),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'REFUNDED', name='payment_status_enum'), server_default='UNPAID', nullable=False, comment='Settlement state of the payment'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Free-text order notes from the customer or cashier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Order placement timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('stock_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Batch PK'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id (M:1 — batch belongs to one product)'),
    sa.Column('batch_number', sa.String(length=100), nullable=False, comment='Manufacturer batch/lot number'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Current available units in this batch'),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Cost price per unit for this batch (IDR)'),
    sa.Column('expiry_date', sa.Date(), nullable=False, comment='Batch expiry date — used for NOTIF-02 alerts and FIFO deduction'),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when batch was received — primary FIFO sort key'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_batches_product_expiry', 'stock_batches', ['product_id', 'expiry_date'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Line-item PK'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='FK → orders.id (M:1 — item belongs to one order)'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='FK → products.id (M:1 — item references one product)'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Number of units purchased for this line item'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Product price at the moment of purchase (IDR) — immutable snapshot'),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False, comment='unit_price × quantity (IDR) — denormalised for query performance'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Prescription PK'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='FK → orders.id. UNIQUE constraint ensures at most one prescription per order (DB-level 1:1 enforcement).'),
    sa.Column('patient_id', sa.BigInteger(), nullable=False, comment='FK → users.id — the patient who uploaded the prescription'),
    sa.Column('pharmacist_id', sa.BigInteger(), nullable=True, comment='FK → users.id (Apoteker role) — NULL until a pharmacist reviews; M:1 because one pharmacist can review many prescriptions'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Storage path of the uploaded prescription photo'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='prescription_status_enum'), server_default='PENDING', nullable=False, comment='Pharmacist review outcome: pending → approved / rejected'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment="Pharmacist's explanation when status = REJECTED"),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when pharmacist approved or rejected the prescription'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when the prescription was first uploaded'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('order_id', name='uq_prescriptions_order_id')
    )
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_stock_batches_product_expiry', table_name='stock_batches')
    op.drop_table('stock_batches')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index('ix_products_fulltext', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops', 'description': 'gin_trgm_ops'})
    op.drop_table('products')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('categories')
    # ### end Alembic commands ###
